### ISSUE TITLE
特定チャンネルのデータが出力されない

### ISSUE THREAD

**Issue by tosono** [kanreisa/Mirakurun#3]
rivarun経由でMirakurunからのストリームデータ取り出しをしていますが、
特定のチャンネルで、Mirakurunからデータが出てきません。

MirakurunをインストールしているPCで、recpt1を実行した場合、データは出てきます。
また、rivarunを使わず、直接REST叩いて、該当チャンネルをGETしても、Mirakurunが無反応です。
statusも帰って来ないので、何が起こっているのか、イマイチ分かりません。

recpt1ではデータが取れるのと、Mirakurunがステータスすら返さない事から、
なんとなく、recpt1のストリームデータをMirakurunが受け取れてないのかな？って思えます。

おかしい所のログを抜き出しました。
[Mirakurun_log.txt](https://github.com/kanreisa/Mirakurun/files/288276/Mirakurun_log.txt)

1～14行　正常
15～28行　なんかおかしい

channnel設定
- name: ショップチャンネル
  type: CS
  channel: CS8
  serviceId: 55
  isDisabled: false

- name: GAORA
  type: CS
  channel: CS12
  serviceId: 254
  isDisabled: false

**Comment by kanreisa** [comment]
```
mirakurun config server
```
で
```
logLevel: 3
```
と設定してからもう一度ログをいただけますでしょうか？

**Comment by tosono** [comment]
遅くなりました。

loglLevel:3で同じ処理を実行した際のログです。
[Mirakurun_log_LV3.txt](https://github.com/kanreisa/Mirakurun/files/289339/Mirakurun_log_LV3.txt)

よろしくお願いします。

**Comment by kanreisa** [comment]
もしかして、エラーログもあるのではないでしょうか？

**Comment by kanreisa** [comment]
修正したので、確認してみてください

**Comment by tosono** [comment]
すみません、エラーも出てました。
Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at Pipe.onread (net.js:563:26)
Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at Pipe.onread (net.js:563:26)

修正して頂いたということなので、試してみます。

**Comment by tosono** [comment]
Mirakurun 1.3.3で確認させて頂きました。
問題無くデータが取れること、確認できました。

**Comment by kanreisa** [comment]
よかったです。
