### ISSUE TITLE
IPv6アドレスでもListenしてほしい

### ISSUE THREAD

**Issue by eru** [kanreisa/Mirakurun#5]
T/O

**Comment by kanreisa** [comment]
理由もいただければ幸いです。

**Comment by eru** [comment]
LAN内にDNSを構築し、ドメインに対してIPv6のレスポンスだけを行う状態（AAAAレコードのみを設定）としている場合に、そのドメイン名に対して、リクエストを送ってもIPv6でMirakurunがListenしていないために、レスポンスを受け取ることが出来ません。

実際には、IPv4アドレスか、それを引けるドメイン名を使用してリクエストすれば、実用的には問題ありませんが、趣味的に上記のような構成を行っているため、ご検討いただけますと幸います。

また、不躾なお願いを理由も書かずに投稿してしまい、お気に害されてましたら申し訳ございません。

**Comment by kanreisa** [comment]
何度か検討はしていますが、今のところ、対応する予定はありません・・・。ごめんなさい m(_ _)m。

代替案としてはxinetd等が使えるとおもいます。

**xinetd** での設定例
```
service mirakurun
{
    type = UNLISTED
    port = 40772
    bind = fe80::
    socket_type = stream
    wait = no
    user = nobody
    redirect = 127.0.0.1 40772
}
```
